<template>
  <v-dialog
    scrollable
    v-model="modelValue"
    fullscreen
    transition="dialog-bottom-transition"
  >
    <v-card>
      <v-toolbar>
        <v-toolbar-title
          >{{ global ? "Global" : "Chat" }} Settings</v-toolbar-title
        >
        <v-toolbar-items>
          <v-select
            v-if="!global"
            style="margin: 4px 0"
            v-model="select"
            :items="['Options', 'History']"
            label="Settings"
          >
          </v-select>
          <v-select
            v-else
            style="margin: 4px 0"
            v-model="select"
            :items="['Options', 'App']"
            label="Settings"
          >
          </v-select>
          <v-btn rounded @click="$emit('update:modelValue', false)">
            <v-icon>mdi-close</v-icon>
          </v-btn>
        </v-toolbar-items>
      </v-toolbar>

      <v-card-text>
        <v-window v-model="select">
          <v-window-item value="Options">
            <v-list>
              <v-list-item>
                <v-select
                  v-model="optionsNow.model"
                  :items="models"
                  label="Model"
                >
                </v-select>
              </v-list-item>
              <v-list-item>
                <v-text-field
                  v-model="optionsNow.maxTokens"
                  label="Maximum Generation Length"
                  type="number"
                  :rules="[rules.integer, rules.maxLength]"
                  hint="The larger the number of tokens, the longer the text generated by the model, but it may consume more tokens."
                ></v-text-field>
              </v-list-item>
              <v-list-item>
                <v-text-field
                  v-model="optionsNow.temperature"
                  label="Temperature"
                  type="number"
                  step="0.1"
                  :rules="[rules.decimal, rules.temperature]"
                  hint="The higher the temperature, the more random the text generated by the model. For creative generation, we recommend setting it to 0.9, while for generation with a clear answer, we suggest setting it to 0."
                ></v-text-field>
              </v-list-item>
              <v-list-item>
                <v-text-field
                  v-model="optionsNow.topP"
                  label="Top P"
                  type="number"
                  step="0.1"
                  :rules="[rules.decimal, rules.topP]"
                  hint="When the value is 0.1, it means only the content that contains the top 10% probability mass is considered for production. It is usually recommended to change this setting or temperature, but not both at the same time."
                ></v-text-field>
              </v-list-item>
              <v-list-item>
                <v-text-field
                  v-model="optionsNow.frequencyPenalty"
                  label="Frequency Penalty"
                  type="number"
                  step="0.1"
                  :rules="[rules.decimal, rules.frequencyPenalty]"
                  hint="When set to a higher value, the generated text will be more elegant, avoiding too common words or phrases."
                ></v-text-field>
              </v-list-item>
              <v-list-item>
                <v-text-field
                  v-model="optionsNow.presencePenalty"
                  label="Presence Penalty"
                  type="number"
                  step="0.1"
                  :rules="[rules.decimal, rules.presencePenalty]"
                  hint="When set to a higher value, the generated text will be more diverse, avoiding repeated content."
                ></v-text-field>
              </v-list-item>
              <v-list-item>
                <v-checkbox
                  v-model="optionsNow.single"
                  label="Single-turn Mode"
                  hint="For less related dialogues, we recommend turning on this mode. Moreover, the number of tokens consumed in this mode will be reduced. However, refreshing messages will not be available in this mode."
                ></v-checkbox>
              </v-list-item>
            </v-list>
          </v-window-item>
          <v-window-item value="History">
            <v-list>
              <v-list-item v-for="item in chats[now].messages" :key="item._id">
                <div>
                  <span class="font-weight-bold">{{
                    item.role === "user"
                      ? user.username
                      : item.role.toLocaleUpperCase()
                  }}</span>
                  <span class="grey--text">
                    - {{ new Date(item.created_at).toLocaleString() }}</span
                  >
                </div>
                <v-card variant="tonal" class="message-content">
                  <div :id="item._id" hidden>
                    {{ item.content }}
                  </div>
                  <div v-html="markdownToHtml(item.content)"></div>
                </v-card>
                <div class="message-actions">
                  <div>
                    <v-btn
                      class="copy-btn"
                      size="x-small"
                      variant="text"
                      @click="copyText(item._id)"
                    >
                      <v-icon>mdi-content-copy</v-icon>
                      Copy
                    </v-btn>
                    <v-btn
                      v-if="item.role !== 'application'"
                      size="x-small"
                      variant="text"
                      @click="item.choose_flag = !item.choose_flag"
                    >
                      <v-icon v-if="item.choose_flag"
                        >mdi-checkbox-marked</v-icon
                      >
                      <v-icon v-else>mdi-checkbox-blank-outline</v-icon>
                      {{ item.choose_flag ? "Check" : "Uncheck" }}
                    </v-btn>
                    <v-btn
                      size="x-small"
                      variant="text"
                      @click="removeMessage(item)"
                    >
                      <v-icon>mdi-delete</v-icon>
                      Delete
                    </v-btn>
                  </div>
                  <!-- if edited, show updated_at -->
                  <span v-if="item.updated_at" style="color: lightgray">
                    - Edited at
                    {{ new Date(item.updated_at).toLocaleString() }}</span
                  >
                </div>
              </v-list-item>
            </v-list>
          </v-window-item>
          <v-window-item value="App">
            <v-text-field
              v-model="auth.key"
              label="Authorization Key"
              hint="Authorization Key is used to access the API."
            ></v-text-field>
          </v-window-item>
        </v-window>
      </v-card-text>
    </v-card>
  </v-dialog>
</template>

<script lang="ts">
import { useChatStore } from "@/store/chat";
import { useUserStore } from "@/store/user";
import { useAppStore } from "@/store/app";
import { storeToRefs } from "pinia";
import { defineComponent, ref } from "vue";
import { getModels } from "@/api/app";
// markdown
import { markdownToHtml, copyText } from "@/utils/markdown";
export default defineComponent({
  name: "Settings",
  props: {
    modelValue: {
      type: Boolean,
      default: false,
    },
    global: {
      type: Boolean,
      default: false,
    },
  },
  emits: ["update:modelValue"],
  computed: {
    optionsNow() {
      if (this.global || this.now == -1) {
        return this.options;
      } else {
        return this.chats[this.now].options;
      }
    },
  },
  setup(props, { emit }) {
    const chatStore = useChatStore();
    const userStore = useUserStore();
    const appStore = useAppStore();
    const { user, auth } = storeToRefs(userStore);
    const { now, chats } = storeToRefs(chatStore);
    const { options } = storeToRefs(appStore);
    const models = ref<string[]>([]);
    const rules = {
      integer: (v: string) => (v && /^\d+$/.test(v)) || "Must be an integer.",
      decimal: (v: string) =>
        (v && /^[+-]?\d+(\.\d{1})?$/.test(v)) ||
        "Maximum precision supported is 0.1.",
      temperature: (v: string) =>
        (v && parseFloat(v) >= 0 && parseFloat(v) <= 2) ||
        "Temperature must be between 0 and 2.",
      topP: (v: string) =>
        (v && parseFloat(v) >= 0 && parseFloat(v) <= 1) ||
        "Top P must be between 0 and 1.",
      frequencyPenalty: (v: string) =>
        (v && parseFloat(v) >= -2 && parseFloat(v) <= 2) ||
        "Frequency Penalty must be between -2 and 2.",
      presencePenalty: (v: string) =>
        (v && parseFloat(v) >= -2 && parseFloat(v) <= 2) ||
        "Presence Penalty must be between -2 and 2.",
      maxLength: (v: string) =>
        (v && parseInt(v) >= 100 && parseInt(v) <= 32768) ||
        "Maximum Generation Length must be between 100 and 32768.",
    };
    const select = ref("Options");
    const removeMessage = (item: message) => {
      if (
        confirm(
          "Are you sure to delete this message? This action cannot be undone!"
        )
      ) {
        chats.value[now.value].messages.splice(
          chats.value[now.value].messages.indexOf(item),
          1
        );
      }
    };
    return {
      rules,
      select,
      user,
      chats,
      options,
      now,
      models,
      auth,
      removeMessage,
      copyText,
      markdownToHtml,
    };
  },
  mounted() {
    getModels().then((res) => {
      this.models = res.data.data.model;
      if (!this.optionsNow.model || this.optionsNow.model === "") {
        this.optionsNow.model = this.models[0];
      }
    });
  },
  watch: {
    optionsNow: {
      handler() {
        const nowOptions = this.optionsNow;
        // vaiidate options
        if (nowOptions.maxTokens === "") {
          nowOptions.maxTokens = "1000";
        }
        if (nowOptions.temperature === "") {
          nowOptions.temperature = "0.9";
        }
        if (nowOptions.topP === "") {
          nowOptions.topP = "1";
        }
        if (nowOptions.frequencyPenalty === "") {
          nowOptions.frequencyPenalty = "0";
        }
        if (nowOptions.presencePenalty === "") {
          nowOptions.presencePenalty = "0";
        }
        // if over max length, set to max length
        if (parseInt(nowOptions.maxTokens!) > 32768) {
          nowOptions.maxTokens = "32768";
        }
        // if over min length, set to min length
        if (parseInt(nowOptions.maxTokens!) < 100) {
          nowOptions.maxTokens = "100";
        }
        // if over max temperature, set to max temperature
        if (parseFloat(nowOptions.temperature!) > 2) {
          nowOptions.temperature = "2";
        }
        // if over min temperature, set to min temperature
        if (parseFloat(nowOptions.temperature!) < 0) {
          nowOptions.temperature = "0";
        }
        // if over max topP, set to max topP
        if (parseFloat(nowOptions.topP!) > 1) {
          nowOptions.topP = "1";
        }
        // if over min topP, set to min topP
        if (parseFloat(nowOptions.topP!) < 0) {
          nowOptions.topP = "0";
        }
        // if over max frequencyPenalty, set to max frequencyPenalty
        if (parseFloat(nowOptions.frequencyPenalty!) > 2) {
          nowOptions.frequencyPenalty = "2";
        }
        // if over min frequencyPenalty, set to min frequencyPenalty
        if (parseFloat(nowOptions.frequencyPenalty!) < -2) {
          nowOptions.frequencyPenalty = "-2";
        }
        // if over max presencePenalty, set to max presencePenalty
        if (parseFloat(nowOptions.presencePenalty!) > 2) {
          nowOptions.presencePenalty = "2";
        }
        // if over min presencePenalty, set to min presencePenalty
        if (parseFloat(nowOptions.presencePenalty!) < -2) {
          nowOptions.presencePenalty = "-2";
        }
        // if over 2 decimal places, set to 2 decimal places
        if (nowOptions.temperature!.includes(".")) {
          nowOptions.temperature = parseFloat(nowOptions.temperature!).toFixed(
            1
          );
        }
        if (nowOptions.topP!.includes(".")) {
          nowOptions.topP = parseFloat(nowOptions.topP!).toFixed(1);
        }
        if (nowOptions.frequencyPenalty!.includes(".")) {
          nowOptions.frequencyPenalty = parseFloat(
            nowOptions.frequencyPenalty!
          ).toFixed(1);
        }
        if (nowOptions.presencePenalty!.includes(".")) {
          nowOptions.presencePenalty = parseFloat(
            nowOptions.presencePenalty!
          ).toFixed(1);
        }
      },
      deep: true,
    },
  },
});
</script>

<style lang="scss" scoped>
// beautify scrollbar
.v-card-text::-webkit-scrollbar {
  width: 6px;
}

.v-card-text::-webkit-scrollbar-track {
  background: rgb(239, 239, 239);
  border-radius: 2px;
}

.v-card-text::-webkit-scrollbar-thumb {
  background: #bfbfbf;
  border-radius: 10px;
}

.v-card-text::-webkit-scrollbar-thumb:hover {
  background: #a6a6a6;
}

.message-actions {
  margin: 5px;
  display: flex;
  justify-content: space-between;
  gap: 5px;
}

.message-content {
  padding: 12px;
  width: fit-content;
}
</style>
